version: '3'
services:
  app:
    container_name: daily
    restart: always
    build: .
    ports:
      - '8001:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'